# ARM-optimierte Docker Compose Template
# Für bessere Kompatibilität mit Apple Silicon (M1/M2/M3)

version: '3.8'

services:
  apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    container_name: redaxo-${INSTANCE_NAME}-apache
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./app:/var/www/html
      - ../../ssl/${INSTANCE_NAME}/cert.crt:/etc/ssl/certs/cert.crt:ro
      - ../../ssl/${INSTANCE_NAME}/private.key:/etc/ssl/private/private.key:ro
    depends_on:
      - mariadb
    networks:
      - redaxo-network
    environment:
      - APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT:-/var/www/html/public}

  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: redaxo-${INSTANCE_NAME}-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../../docker-templates/mariadb/my.cnf:/etc/mysql/my.cnf:ro
    networks:
      - redaxo-network

  # ARM-kompatible PHPMyAdmin Alternative
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: redaxo-${INSTANCE_NAME}-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - redaxo-network

  # ARM-kompatible E-Mail-Test-Tool mit Mailpit
  mailpit:
    image: axllent/mailpit:latest
    container_name: redaxo-${INSTANCE_NAME}-mailpit
    ports:
      - "${MAILPIT_PORT}:8025"  # Web UI
      - "${SMTP_PORT}:1025"     # SMTP
    networks:
      - redaxo-network
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

networks:
  redaxo-network:

volumes:
  mariadb_data:
